import type { Slide } from "./types";

/** Session 4 — Quick quiz (~5 minutes) on mental models from Sessions 1–3. */
export const session4Quiz: Slide[] = [
  {
    id: "s4-title",
    variant: "title",
    title: "LOMEdu",
    subtitle: "Session 4: Quiz",
    tagline: "Check the mental models from Sessions 1–3 — about 5 minutes",
  },
  {
    id: "s4-how-to-run",
    variant: "bullets",
    title: "How this quiz works",
    intro: "You will see multiple-choice questions. For each one:",
    bullets: [
      "Read the question and options — take a few seconds to decide",
      "Signal your choice as A, B, C, or D (hands, fingers, or your group’s usual signal)",
      "Press space to reveal the marked answer, then press space again to go to the next slide",
    ],
    footer: "There is no grade here — wrong answers are useful for discussion.",
  },
  {
    id: "s4-q1",
    variant: "quiz",
    title: "Question 1",
    question: "In the “new mindset,” what is AI best described as?",
    optionA: "A search engine",
    optionB: "A calculator",
    optionC: "A collaborator",
    optionD: "A storage tool",
    correctLetter: "C",
    footer: "AI sits beside you — you still judge quality, safety, and intent.",
  },
  {
    id: "s4-q2",
    variant: "quiz",
    title: "Question 2",
    question: "What is vibe coding?",
    optionA: "Writing every line of code by hand",
    optionB: "Designing UI mockups only",
    optionC: "Describing ideas and constraints in plain language — then reviewing what AI builds",
    optionD: "Debugging without reading error messages",
    correctLetter: "C",
  },
  {
    id: "s4-q3",
    variant: "quiz",
    title: "Question 3",
    question: "In our restaurant analogy, Supabase (Postgres + APIs) is most like…",
    optionA: "The kitchen",
    optionB: "The pantry — durable ingredients you fetch and put back carefully",
    optionC: "The front door",
    optionD: "The paper menu only",
    correctLetter: "B",
  },
  {
    id: "s4-q4",
    variant: "quiz",
    title: "Question 4",
    question: "Generative AI is best characterized as…",
    optionA: "A system that mostly ranks existing web pages",
    optionB: "Hardware that makes your laptop faster",
    optionC: "A system that produces new content from your prompt, examples, or constraints",
    optionD: "A spreadsheet formula engine",
    correctLetter: "C",
  },
  {
    id: "s4-q5",
    variant: "quiz",
    title: "Question 5",
    question: "Agentic AI usually implies which pattern?",
    optionA: "One short answer with no follow-up steps",
    optionB: "Multi-step work toward a goal — tools, planning, checkpoints",
    optionC: "Only image generation",
    optionD: "Offline-only calculators",
    correctLetter: "B",
  },
  {
    id: "s4-q6",
    variant: "quiz",
    title: "Question 6",
    question: "In the same analogy, the server (your API / backend logic) is like…",
    optionA: "The dining room where guests sit",
    optionB: "The pantry shelves",
    optionC: "The kitchen — where orders are cooked and rules are applied",
    optionD: "The restaurant’s Instagram page",
    correctLetter: "C",
  },
  {
    id: "s4-q7",
    variant: "quiz",
    title: "Question 7",
    question: "GitHub in our story maps best to…",
    optionA: "The dishwasher only",
    optionB: "The recipe binder and change history — how instructions evolve safely",
    optionC: "The customer’s credit card",
    optionD: "The food delivery drone",
    correctLetter: "B",
  },
  {
    id: "s4-q8",
    variant: "quiz",
    title: "Question 8",
    question: "After AI edits your project, what should you do every time before you trust it?",
    optionA: "Ship immediately to production",
    optionB: "Change nothing — the model is always right",
    optionC: "Review the diff, run tests if you have them, and think about security and edge cases",
    optionD: "Delete Git history",
    correctLetter: "C",
  },
  {
    id: "s4-q9",
    variant: "quiz",
    title: "Question 9",
    question: "The “old way” of coding often gated progress on…",
    optionA: "Memorizing syntax and tooling before the idea felt real",
    optionB: "Having perfect design taste on day one",
    optionC: "Avoiding all documentation",
    optionD: "Writing zero lines of code",
    correctLetter: "A",
  },
  {
    id: "s4-q10",
    variant: "quiz",
    title: "Question 10",
    question: "AI-assisted development means you still own…",
    optionA: "Only the font choice",
    optionB: "Nothing — the AI owns the product",
    optionC: "Architecture, correctness, security, and ethics — the AI accelerates drafts",
    optionD: "Only the README title",
    correctLetter: "C",
  },
  {
    id: "s4-q11",
    variant: "quiz",
    title: "Question 11",
    question: "A simple way to describe an API is…",
    optionA: "A secret password for Wi‑Fi",
    optionB: "A structured way for programs to request actions or data from another system",
    optionC: "Only a mobile app icon",
    optionD: "A type of computer monitor",
    correctLetter: "B",
  },
  {
    id: "s4-q12",
    variant: "quiz",
    title: "Question 12",
    question: "Deploying your app is closest to…",
    optionA: "Deleting the database",
    optionB: "Writing pseudocode no one runs",
    optionC: "Grand opening — making a version available for real users (with monitoring and fixes after)",
    optionD: "Buying a domain name only, with no hosting",
    correctLetter: "C",
  },
  {
    id: "s4-recap",
    variant: "recap",
    title: "Wrap-up",
    bullets: [
      "AI as collaborator; vibe coding = intent + review, not autopilot",
      "Restaurant map: browser (front), server (kitchen), database / Supabase (pantry), GitHub (recipes + history)",
      "Generative vs agentic: new artifact vs multi-step pursuit of a goal",
    ],
    footer: "Nice work — carry these checks into every lab.",
  },
];
